version: '3.8'

services:
  netwatch:
    build: .
    container_name: netwatch
    volumes:
      - ./captures:/app/captures
      - ./logs:/app/logs
      - ./reports:/app/reports
    ports:
      - "8502:8502"
    network_mode: "host"  # Required for network scanning
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
